.

diff --git a/ntfs-gen-from-folder b/ntfs-gen-from-folder
--- a/ntfs-gen-from-folder
+++ b/ntfs-gen-from-folder
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Sizes in megabytes
-START_SIZE=16000
+START_SIZE=13000
 INCREASE_SIZE=1000
 
 # $1: Filename
@@ -62,6 +62,8 @@ copy_data() {
 failed() {
     echo 'An error occurred'
     (cd "${TMPDIR}" && bash)
+    ntfs_unmount "${NTFS_FILE}"
+    rm -rf "${TMPDIR}"
     exit
 }
 
@@ -75,7 +77,11 @@ mkdir -p "${MOUNT_DIR}"
 
 create_ntfs_file "${NTFS_FILE}" "${SOURCE_DIR##*/}" "${START_SIZE}" || failed
 ntfs_mount "${NTFS_FILE}" "${MOUNT_DIR}" || failed
-cp -vrf "${SOURCE_DIR}"/* "${MOUNT_DIR}" || failed
+#cp -vrf "${SOURCE_DIR}"/* "${MOUNT_DIR}" || failed
+rsync --info=progress2 --no-inc-recursive --inplace --size-only --delete-before --whole-file -r "${SOURCE_DIR}/" "${MOUNT_DIR}" || failed
+sleep 5
+sync
+sleep 5
 ntfs_unmount "${NTFS_FILE}" || failed
 ntfs_shrink_fit "${NTFS_FILE}" || failed
 ntfs_finish "${NTFS_FILE}" || failed
